name: onvif
version: 4.2.0
summary: onvif viewer
description: |
  onvif tools
confinement: strict
base: core22

parts:
  onvif:
    plugin: dump
    source: ./
    after: [desktop-qt5]
    stage-packages:
      - ffmpeg
      - x264
      - x265
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5gui5
      - libqt5xml5
      - qtbase5-dev
      - libqt5opengl5

apps:
  onvif:
    command: desktop-launch $SNAP/usr/bin/onvif
    extensions:
      # - kde-neon
      - gnome
    plugs:
      - opengl
      - network
      - network-bind
      - desktop
      - desktop-legacy
