name: onvif
version: 4.2.0
summary: onvif viewer
description: |
  onvif tools
confinement: strict
base: core24

parts:
  onvif:
    plugin: dump
    source: ./
    stage-packages:
      - ffmpeg
      - x264
      - x265
apps:
  onvif:
    command: onvif
    extensions:
      - kde-neon
    plugs:
      - kde-frameworks-5-plug
      - opengl
      - network
      - network-bind
      - pulseaudio
      - x11
      - display-control
      - mir
