name: onvif
version: 4.2.0
summary: onvif viewer
description: |
  onvif tools
confinement: strict
base: core22

parts:
  onvif:
    plugin: dump
    source: ./
    stage-packages:
      - ffmpeg
      - x264
      - x265
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5gui5
      - libgdk-pixbuf2.0-0
      - libqt5svg5
      - appmenu-qt5
      - fcitx-frontend-qt5

apps:
  onvif:
    command: onvif
    extensions:
      # - kde-neon
      - gnome
    plugs:
      - kde-frameworks-5-plug
      - opengl
      - network
      - network-bind
      - pulseaudio
      - x11
      - display-control
      - mir
      - wayland
