name: onvif
version: 4.2.0
summary: onvif viewer
description: |
  onvif tools
grade: stable
confinement: strict
base: core22

apps:
  onvif:
    command: onvif
    # extensions:
    #   # - kde-neon
    #   - gnome
    plugs:
      - opengl
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - unity7
      - x11

parts:
  onvif:
    plugin: dump
    source: ./
    build-packages:
      - libpulse-dev
      - libx264-dev
      - libx264-dev
      - libffmpegthumbnailer-dev
    stage-packages:
      - ffmpeg
      - x264
      - x265
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5gui5
      - libqt5xml5
      - qtbase5-dev
      - libqt5opengl5
      - libpulse-dev
      - libpulse0
      - libpulse-mainloop-glib0
      - libffmpegthumbnailer4v5
    after:
      - desktop-qt5

  desktop-qt5:
      source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
      source-subdir: qt
      plugin: make
      make-parameters: ["FLAVOR=qt5"]
      build-packages:
        - build-essential
        - qtbase5-dev
        - dpkg-dev
      stage-packages:
        - libxkbcommon0
#        - ttf-ubuntu-font-family
        - dmz-cursor-theme
        - light-themes
        - adwaita-icon-theme
        - gnome-themes-standard
        - shared-mime-info
        - libqt5gui5
        - libgdk-pixbuf2.0-0
#        - libgtk2.0-0 # snapcraft was complaining about missing libgtk-x11-2.0.so.0
        - libqt5svg5 # for loading icon themes which are svg
#        - appmenu-qt5
        - locales-all
        - xdg-user-dirs
        - fcitx-frontend-qt5
        - libglib2.0-0 # we need this or under Gnome the file chooser will crash the app!
