name: onvif
version: 4.2.0
summary: onvif viewer
description: |
  onvif tools
confinement: strict
base: core20

parts:
  onvif:
    plugin: dump
    source: ./
    stage-packages:
      - ffmpeg
      - x264
      - x265
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5gui5
      - libqt5xml5
      - qtbase5-dev
      - libqt5opengl5
    after:
      - desktop-qt5

  desktop-qt5:
    source: https://github.com/ubuntu/snapcraft-desktop-helpers.git
    source-branch: stable
    source-subdir: qt
    plugin: make


apps:
  onvif:
    command: desktop-launch $SNAP/usr/bin/onvif
    # extensions:
    #   # - kde-neon
    #   - gnome
    plugs:
      - opengl
      - network
      - network-bind
      - desktop
      - desktop-legacy
      - x11
