name: Release

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  linux:
    name: Linux
    runs-on: ubuntu-latest
    env:
      SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
    steps:
      - uses: actions/checkout@v4
      - name: Install snapcraft
        run: |
          sudo snap install snapcraft --classic
      - run: hash -r
      - name: Setup LXD
        uses: canonical/setup-lxd@v0.1.1
        with:
          channel: latest/stable
      - name: run snapcraft
        run: |
          snapcraft --use-lxd
      - run: snapcraft upload --release=stable *.snap
